config/urls.py
"""
Настройка URL-адресов для проекта config.

Список `urlpatterns` перенаправляет URL-адреса в представления. Для получения дополнительной информации, пожалуйста, смотрите:
 https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
 1. Добавьте импорт: из my_app импортируйте представления
 2. Добавьте URL-адрес в urlpatterns: path(", views.home, name="home")
Представления на основе классов
 1. Добавьте импорт: из other_app.views импортируйте Home
 2. Добавьте URL-адрес в urlpatterns: path(", Home.as_view(), name="home")
Включая другой URLconf
 1. Импортируйте функцию includes(): из django.urls импортируйте includes, path
 2. Добавьте URL-адрес в urlpatterns: path('blog/', includes('blog.urls'))
"""
"""Отслеживание url-адресов"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# urls для административной панели Django
urlpatterns = [
                  path('admin/', admin.site.urls),  # URL для административной панели Django
                  path('', include('dogs.urls', namespace='dogs')),  # URL для приложения dogs
                  path('users/', include('users.urls', namespace='users')),  # URL для приложения users)
                  path('reviews/', include('reviews.urls', namespace='reviews')),  # URL для приложения reviews)
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавляем медиафайлы

dogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page,never_cache

from dogs.models import Category
from dogs.views import index, DogListView, DogCreateView, DogDetailView, DogUpdateView, DogDeleteView, \
    DogCategoryListView, CategoryListView, DogDeactiveListView, DogSearchListView, dog_toggle_activity, \
    CategorySearchListView
from dogs.apps import DogsConfig

app_name = DogsConfig.name  # DogsConfig имя приложения

urlpatterns = [
    path('', cache_page(60)(index), name='index'),  # url на главную страницу  /кешируется страница 
    path('categories/', cache_page(60)(CategoryListView.as_view()), name='categories'),  # url на страницу с информацией о всех категориях
    path('categories/<int:pk>/dogs/', DogCategoryListView.as_view(), name='category_dogs'), # url на страницу с информацией о питомцах определенной кат
    path('dogs/', DogListView.as_view(), name='list_dogs'),  # url на страницу с информацией о всех питомцах (вместо pk)
    path('dogs/deactivated/', DogDeactiveListView.as_view(), name='deactivated_list_dogs'),  # url на страницу с информацией о всех не активных питомцах (вместо pk)
    path('dogs/search/', DogSearchListView.as_view(), name='search_dogs'),
    path('categories/search/', CategorySearchListView.as_view(), name='search_category'),
    path('dogs/create', DogCreateView.as_view(), name='create_dog'), # url на страницу создания нового питомца
    path('dogs/detail/<int:pk>/', DogDetailView.as_view(), name='detail_dog'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='update_dog'), # /не кешируется страница
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='toggle_activity_dog'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='delete_dog')
]

reviews/urls.py
from django.urls import path

from reviews.apps import ReviewsConfig
from reviews.views import ReviewListView, DeactivatedDogReviewListView, ReviewDetailView, ReviewUpdateView, \
    ReviewDeleteView, ReviewCreateView, review_toggle_activity

app_name = ReviewsConfig.name  # for backwards compatibility

urlpatterns = [

    path('', ReviewListView.as_view(), name='list_reviews'),
    path('reviews/deactivated/', DeactivatedDogReviewListView.as_view(), name='deactivated_reviews_list'),
    path('reviews/create/', ReviewCreateView.as_view(), name='create_review'),
    path('reviews/detail/<slug:slug>/', ReviewDetailView.as_view(), name='detail_review'),
    path('reviews/update/<slug:slug>/', ReviewUpdateView.as_view(), name='create_update_review'),
    path('reviews/delete/<slug:slug>/', ReviewDeleteView.as_view(), name='delete_review'),
    path('reviews/toggle/<slug:slug>/', review_toggle_activity, name='toggle_activity_review'),
]

reviews/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from users.models import NULLABLE
from dogs.models import Dog


class Review(models.Model):
    # Модель отзыва
    title = models.CharField(max_length=150, verbose_name='title')  # title
    slug = models.SlugField(max_length=25, unique=True, db_index=True, verbose_name='URL')  # slug
    content = models.TextField(verbose_name='Содержимое')  # content
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)  # datetime
    sign_of_review = models.BooleanField(default=True, verbose_name="Активный")  # sign_of_review
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                               verbose_name='Автор')  # author
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, verbose_name='Собака')  # Dog

    def __str__(self):
        # Возвращает заголовок отзыва в виде строки
        return f'{self.title}'

    def get_absolute_url(self):
        # Возвращает абсолютный URL для страницы детального отзыва
        return reverse('reviews:detail_review', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

reviews/forms.py
from django import forms
from reviews.models import Review
from dogs.forms import StyleFromMixin


class ReviewForm(StyleFromMixin, forms.ModelForm):
    # Создаем форму для добавления/редактирования отзыва с указанными полями
    title=forms.CharField(max_length=150,label='Заголовок_формы')
    content=forms.TextInput()
    slug=forms.SlugField(max_length=20, initial='temp_slug', widget=forms.HiddenInput())
    class Meta:
        model = Review
        fields = ('dog','title','content','slug')

reviews/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.http import HttpResponseForbidden
from django.shortcuts import reverse, get_object_or_404, redirect
from django.views.generic import CreateView, CreateView, DeleteView, UpdateView, ListView, DetailView
from django.core.exceptions import PermissionDenied

from reviews.models import Review
from users.models import UserRoles
from reviews.forms import ReviewForm
from reviews.utils import slug_generation


class ReviewListView(LoginRequiredMixin, ListView):
    """Отображение всех активных отзывов"""
    model = Review
    paginate_by = 3
    extra_context = {
        'title': 'Питомник - Все отзывы по собаке'
    }
    template_name = 'reviews/reviews_list.html'

    def get_queryset(self):
        # фильтр по активным отзывам
        queryset = super().get_queryset()
        # queryset = queryset.filter(dog_pk=self.kwargs.get('pk'))
        queryset = queryset.filter(sign_of_review=True)
        return queryset


class DeactivatedDogReviewListView(LoginRequiredMixin, ListView):
    """Отображение всех неактивных отзывов"""
    model = Review
    extra_context = {
        'title': 'Неактивные отзывы'
    }
    template_name = 'reviews/reviews_list.html'

    def get_queryset(self):
        # фильтр по неактивным отзывам
        queryset = super().get_queryset()
        # queryset = queryset.filter(dog_pk=self.kwargs.get('pk'))
        queryset = queryset.filter(sign_of_review=False)

        return queryset


class ReviewCreateView(CreateView):
    """Создание нового отзыва"""
    model = Review
    form_class = ReviewForm
    template_name ='reviews/review_create_update.html'

    def form_valid(self, form):
        # валидация формы, где прописаны:
        # изменение slug для уникальности URL-адреса,
        # проверка наличия прав пользователя
        if self.request.user.role not in [UserRoles.USER, UserRoles.ADMIN]:
            return HttpResponseForbidden()
        self.object = form.save()
        print(self.object.slug)
        if self.object.slug == "temp_slug":
            self.object.slug = slug_generation()
            print(self.object.slug)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

class ReviewDetailView(LoginRequiredMixin,DetailView):
    """Просмотр одного отзыва"""
    model = Review
    template_name ='reviews/review_detail.html'

class ReviewUpdateView(LoginRequiredMixin,UpdateView):
    """Редактирование отзыва"""
    model = Review
    form_class = ReviewForm
    template_name ='reviews/review_create_update.html'

    def form_valid(self,form):
        # валидация формы, где прописаны:
        # изменение slug для уникальности URL-адреса,
        # проверка наличия прав пользователя
        if self.request.user.role not in [UserRoles.USER, UserRoles.ADMIN]:
            return HttpResponseForbidden()
        self.object = form.save()
        print(self.object.slug)
        if self.object.slug == "temp_slug":
            self.object.slug = slug_generation()
            print(self.object.slug)
        self.object.autor =self.request.user
        self.object.save()
        return super().form_valid(form)


    def get_success_url(self):
        # перенаправление на страницу с детальным описанием отзыва после редактирования.
        return reverse('reviews:detail_review', args=[self.kwargs.get('slug')])

    def get_object(self, queryset=None):
        # Проверка наличия прав для просмотра отзыва.
        self.object = super().get_object(queryset)
        if self.object.author != self.request.user and self.request.user not in [UserRoles.ADMIN, UserRoles.MODERATOR]:
            raise PermissionDenied()
        return self.object

class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    """Удаление отзыва"""
    model = Review
    template_name ='reviews/review_delete.html'
    permission_required = 'reviews.delete_review'

    def get_success_url(self):
        # перенаправление на страницу со списком отзывов после удаления.
        return reverse('reviews:list_reviews')


def review_toggle_activity(request, slug):

    review_item = get_object_or_404(Review, slug=slug)
    if review_item.sign_of_review:
        review_item.sign_of_review = False
        review_item.save()
        return redirect(reverse('reviews:deactivated_reviews_list'))
    else:
        review_item.sign_of_review = True
        review_item.save()
        return redirect(reverse('reviews:list_reviews'))

reviews/templates/reviews/review_create_update.html
{% extends 'dogs/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование отзыва
                {% else %}
                Новый отзыв
                {% endif %}
            </div>

            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-outline-success"

                       value="{% if object %}Сохранить{% else %} Добавить{% endif %}">
                {% if object %}
                <a href="{% url 'reviews:toggle_activity_review' object.slug %}"
                   class="btn btn-outline-warning float-right">
                    {% if object.sign_of_review %}
                    Деактивировать
                    {% else %}
                    Активировать
                    {% endif %}
                </a>
                {% endif %}
            </div>
            <div class="card-footer">
                <a href="{% url 'reviews:list_reviews' %}" class="btn btn-outline-primary"><< Назад</a>
                {% if object and user.is_superuser %}
                <a href="{% url 'reviews:delete_review' object.slug %}" class="btn btn-outline-danger float-right">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

reviews/templates/reviews/review_delete.html
{% extends 'dogs/base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Вы уверены что хотите удалить отзыв
                {% endif %}
            </div>
            <div class="card-body">
                <p class="card-text">{{ object.dog.name|title }}</p>
                <p class="card-text">{{ object.title|title }}</p>
            </div>
            <div class="card-footer">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-danger float-right">
                    {% if object %}
                    Удалить
                    {% endif %}
                </button>
                <a href="{% url 'reviews:create_update_review' object.slug %}" class="btn btn-outline-primary"><< Назад</a>
            </div>

        </div>
    </div>
</form>
{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card-md-12 box-shadow">
            <div class="card-header">
                <p class="card-text">
                    <td>Отзыв</td>
                    {{ object.dog.name }} {{ object.title }}
                </p>
            </div>
            <div class="card-body">
                <p class="card-text">
                    <td>Текст отзыва</td>
                    {{ object.content }}
                </p>
                <span class="text-muted"><td>Дата создания</td>{{ object.created }}</span>
                <br>
                <span class="text-muted"><td>Автор:</td>{{ object.author|default:"Аноним" }}</span>
            </div>
            <div class="card-footer">
                <a href="{% url 'reviews:list_reviews' %}"><< Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

reviews/templates/reviews/reviews_list.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'reviews/includes/inc_reviews_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' %}
    <a href="{% url 'reviews:create_review' %}" class="btn btn-outline-primary m-2 float-left">Добавить отзыв</a>
    <a href="{% url 'reviews:deactivated_reviews_list' %}" class="btn btn-outline-secondary m-2 float-right">Неактивные отзывы</a>
    <a href="{% url 'reviews:list_reviews' %}" class="btn btn-outline-success m-2 float-right">Активные отзывы</a>
</div>
{% endblock %}