config/urls.py
"""
Настройка URL-адресов для проекта config.

Список `urlpatterns` перенаправляет URL-адреса в представления. Для получения дополнительной информации, пожалуйста, смотрите:
 https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
 1. Добавьте импорт: из my_app импортируйте представления
 2. Добавьте URL-адрес в urlpatterns: path(", views.home, name="home")
Представления на основе классов
 1. Добавьте импорт: из other_app.views импортируйте Home
 2. Добавьте URL-адрес в urlpatterns: path(", Home.as_view(), name="home")
Включая другой URLconf
 1. Импортируйте функцию includes(): из django.urls импортируйте includes, path
 2. Добавьте URL-адрес в urlpatterns: path('blog/', includes('blog.urls'))
"""
"""Отслеживание url-адресов"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# urls для административной панели Django
urlpatterns = [
                  path('admin/', admin.site.urls),  # URL для административной панели Django
                  path('', include('dogs.urls', namespace='dogs')),  # URL для приложения dogs
                  path('users/', include('users.urls', namespace='users')),  # URL для приложения users)
                  path('reviews/', include('reviews.urls', namespace='reviews')),  # URL для приложения reviews)
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавляем медиафайлы

dogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page,never_cache

from dogs.models import Category
from dogs.views import index, DogListView, DogCreateView, DogDetailView, DogUpdateView, DogDeleteView, \
    DogCategoryListView, CategoryListView, DogDeactiveListView, DogSearchListView, dog_toggle_activity, \
    CategorySearchListView
from dogs.apps import DogsConfig

app_name = DogsConfig.name  # DogsConfig имя приложения

urlpatterns = [
    path('', cache_page(60)(index), name='index'),  # url на главную страницу  /кешируется страница 
    path('categories/', cache_page(60)(CategoryListView.as_view()), name='categories'),  # url на страницу с информацией о всех категориях
    path('categories/<int:pk>/dogs/', DogCategoryListView.as_view(), name='category_dogs'), # url на страницу с информацией о питомцах определенной кат
    path('dogs/', DogListView.as_view(), name='list_dogs'),  # url на страницу с информацией о всех питомцах (вместо pk)
    path('dogs/deactivated/', DogDeactiveListView.as_view(), name='deactivated_list_dogs'),  # url на страницу с информацией о всех не активных питомцах (вместо pk)
    path('dogs/search/', DogSearchListView.as_view(), name='search_dogs'),
    path('categories/search/', CategorySearchListView.as_view(), name='search_category'),
    path('dogs/create', DogCreateView.as_view(), name='create_dog'), # url на страницу создания нового питомца
    path('dogs/detail/<int:pk>/', DogDetailView.as_view(), name='detail_dog'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='update_dog'), # /не кешируется страница
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='toggle_activity_dog'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='delete_dog')
]

reviews/urls.py
from django.urls import path

from reviews.apps import ReviewsConfig
from reviews.views import ReviewListView, DeactivatedDogReviewListView, ReviewDetailView, ReviewUpdateView, \
    ReviewDeleteView, ReviewCreateView, review_toggle_activity

app_name = ReviewsConfig.name  # for backwards compatibility

urlpatterns = [

    path('', ReviewListView.as_view(), name='list_reviews'),
    path('reviews/deactivated/', DeactivatedDogReviewListView.as_view(), name='deactivated_reviews_list'),
    path('reviews/create/', ReviewCreateView.as_view(), name='create_review'),
    path('reviews/detail/<slug:slug>/', ReviewDetailView.as_view(), name='detail_review'),
    path('reviews/update/<slug:slug>/', ReviewUpdateView.as_view(), name='create_update_review'),
    path('reviews/delete/<slug:slug>/', ReviewDeleteView.as_view(), name='delete_review'),
    path('reviews/toggle/<slug:slug>/', review_toggle_activity, name='toggle_activity_review'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_generate_new_password, UserRegisterView, UserLoginView, UserProfileView, UserUpdateView, \
    UserPasswordChangeView, UserLogoutView, UserListView, UserViewProfileView

app_name = UsersConfig.name

urlpatterns = [
    # работа с аккаунтом
    path('', UserLoginView.as_view(), name="login_user"),
    path('logout/', UserLogoutView.as_view(), name='logout_user'),
    path('register/', UserRegisterView.as_view(), name='register_user'),
    path('profile/', UserProfileView.as_view(), name='profile_user'),
    path('update/', UserUpdateView.as_view(), name='update_user'),
    path('change_password/', UserPasswordChangeView.as_view(), name='change_password_user'),
    path('profile/genpassword/', user_generate_new_password, name='generate_new_password_user'),

    # просмотр других пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('profile/<int:pk>/', UserViewProfileView.as_view(), name='profile_user_view'),
]

dogs/forms.py
import datetime

from django import forms

from dogs.models import Dog, Parent
from users.forms import StyleFromMixin


class DogForm(StyleFromMixin, forms.ModelForm):
    # Создаем форму для добавления/редактирования питомца с указанными полями
    class Meta:
        model = Dog
        exclude = ('owner', 'is_active', 'views')

    def clean_birth_date(self):
        # Проверка соответствия даты рождения питомца
        cleaned_data = self.cleaned_data['birth_date']
        if cleaned_data is None:
            return None
        now_year = datetime.datetime.now().year
        if now_year - cleaned_data.year > 100:
            raise forms.ValidationError(
                'Возраст питомца не может быть больше 100 лет')
        return cleaned_data


class DogAdminForm(StyleFromMixin, forms.ModelForm):
    # Создаем форму для редактирования питомца с указанными полями
    class Meta:
        model = Dog
        exclude = '__all__'

    # @staticmethod
    # def clean_birth_date():
    #     DogForm.clean_birth_date()
    def clean_birth_date(self):
        cleaned_data = self.cleaned_data['birth_date']
        if cleaned_data is None:
            return None
        now_year = datetime.datetime.now().year
        if now_year - cleaned_data.year > 100:
            raise forms.ValidationError(
                'Возраст питомца не может быть больше 100 лет')
        return cleaned_data


class ParentForm(StyleFromMixin, forms.ModelForm):
    # Создаем форму для добавления/редактирования родителя с указанными полями
    class Meta:
        model = Parent
        fields = '__all__'

dogs/views.py
from lib2to3.fixes.fix_input import context

from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
# миксин который выполняет классы только тогда когда пользователь зарегистрированный
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# from django.http import Http404, HttpResponseForbidden
from django.forms import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.db.models import Q

from dogs.services import send_views_mail
from users.models import UserRoles

from dogs.models import Category, Dog, Parent
from dogs.forms import DogForm, ParentForm, DogAdminForm


def index(request):
    """ Показывает главную страницу с информацией о категориях и питомниках."""
    context = {
        # отображение категорий ограничено тремя
        'object_list': Category.objects.all()[:3],
        'title': "Питомник - Главная"
    }
    return render(request, 'dogs/index.html', context)


class CategoryListView(LoginRequiredMixin, ListView):
    """ Список всех категорий."""
    model = Category
    extra_context = {
        'title': 'Питомник - Все наши породы'
    }
    template_name = 'dogs/categories.html'

class CategorySearchListView(LoginRequiredMixin, ListView):
    """ Показывает страницу с результатами поиска собак."""
    model = Category
    template_name = 'dogs/categories.html'
    extra_context = {
        'title': 'Результаты поискового запроса',
    }
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list =Category.objects.filter(Q(name__icontains=query))
        return object_list


class DogDeactiveListView(LoginRequiredMixin, ListView):

    model = Dog
    extra_context = {
        'title': 'Питомник - неактивные собаки'
    }
    template_name = 'dogs/dogs.html'

    def get_queryset(self):
        # Показывает для тех учеток неактивных собак, и для пользователей своих неактивных собак
        queryset = super().get_queryset()
        if self.request.user.role in [UserRoles.MODERATOR, UserRoles.ADMIN]:
            queryset = queryset.filter(is_active=False)
        if self.request.user.role == UserRoles.USER:
            queryset = queryset.filter(is_active=False, owner=self.request.user)
        return queryset


class DogSearchListView(LoginRequiredMixin, ListView):
    """ Показывает страницу с результатами поиска собак."""
    model = Dog
    template_name = 'dogs/dogs.html'
    extra_context = {
        'title': 'Результаты поискового запроса',
    }
    def get_queryset(self):
        # Фильтр по вводимым данным в строку поиска
        query = self.request.GET.get('q')
        object_list =Dog.objects.filter(Q(name__icontains=query), is_active=True)
        return object_list

class DogCategoryListView(ListView):
    """ Показывает страницу с информацией о питомцах определенной категории."""
    model = Dog
    template_name = 'dogs/dogs.html'

    def get_queryset(self):
        # Фильтр показывает только активных собак определенной категории
        queryset = super().get_queryset().filter(
            category_id=self.kwargs.get('pk'), is_active=True
        )
        # Опция которая позволяет закрыть страницу от пользователя (будет видить только своих собак)
        # if not self.request.user.is_staff:
        #     queryset = queryset.filter(owner=self.request.user)

        return queryset


class DogListView(ListView):
    """ Показывает список всех питомцев."""
    model = Dog
    paginate_by = 3
    extra_context = {
        'title': "Питомник - Все наши собаки",
    }
    template_name = 'dogs/dogs.html'

    def get_queryset(self):
        # Фильтр показывает только активных собак
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class DogCreateView(LoginRequiredMixin, CreateView):
    """ Страница создания нового питомца."""
    model = Dog
    form_class = DogForm
    template_name = 'dogs/create.html'
    success_url = reverse_lazy('dogs:list_dogs')

    def form_valid(self, form):
        # Добавляем текущего пользователя в поле "владелец" нового питомца
        if self.request.user.role != UserRoles.USER:  # ограничивает служебные учетки
            raise PermissionDenied()
            # return HttpResponseForbidden("У вас нет прав для добавление собак") # только если ожидается перенаправление
        # form.instance.owner = self.request.user
        self.object = form.save()  # получаем объект из формы
        # добавляем владельца собаки из зарегистрированного пользователя
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class DogDetailView(LoginRequiredMixin, DetailView):
    """ Страница детальной информации о питомца."""
    model = Dog
    template_name = 'dogs/detail.html'

    def get_context_data(self, **kwargs):
        # Добавляем к контексту информацию о количестве просмотров питомца
        context_data = super().get_context_data(**kwargs)
        object = self.get_object()
        context_data['title'] = f'{object.name} {object.category}'
        dog_object_increase = get_object_or_404(Dog, pk=object.pk)
        # if object.owner  != self.request.user and self.request.user.role not in [UserRoles.ADMIN, UserRoles.MODERATOR]:
        if object.owner != self.request.user:
            dog_object_increase.views_count()
        if object.owner:
            object_owner_email = object.owner.email
            if dog_object_increase.views % 100 == 0 and dog_object_increase.views != 0:
                send_views_mail(dog_object_increase, object_owner_email, dog_object_increase.views)
        return context_data


class DogUpdateView(LoginRequiredMixin, UpdateView):
    """ Страница изменения информации о питомце."""
    model = Dog
    template_name = 'dogs/update.html'

    def get_success_url(self):
        # return reverse('dogs:detail_dog', args=[self.object.pk])  # Переходим на страницу детальной информации питомца после редактирования
        # Переходим на страницу детальной информации питомца после редактирования
        return reverse('dogs:detail_dog', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        # Если питомец не принадлежит текущему пользователю или не пользователю администратор, то возбуждаем ошибку
        self.object = super().get_object(queryset)
        # if self.object.owner != self.request.user and not self.request.user.is_staff:
        if self.object.owner != self.request.user and self.request.user.role != UserRoles.ADMIN:
            # raise Http404
            raise PermissionDenied()
        return self.object

    def get_context_data(self, **kwargs):
        # Добавляем форму для редактирования родителей питомца
        contex_data = super().get_context_data(**kwargs)
        ParentFormset = inlineformset_factory(Dog, Parent, form=ParentForm, extra=1)
        if self.request.method == 'POST':
            formset = ParentFormset(self.request.POST, instance=self.object)
        else:
            formset = ParentFormset(instance=self.object)
        contex_data['formset'] = formset
        return contex_data

    def form_valid(self, form):
        # форма валидации для подставления родословной
        contex_data = self.get_context_data()
        formset = contex_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        # Выбираем форму для редактирования питомца в зависимости от роли пользователя
        dog_forms = {
            'admin': DogAdminForm,
            'moderator': DogForm,
            'user': DogForm,
        }
        user_role = self.request.user.role
        dog_form_class = dog_forms[user_role]
        return dog_form_class


class DogDeleteView(PermissionRequiredMixin, DeleteView):
    """ Страница удаления питомца."""
    model = Dog
    template_name = 'dogs/delete.html'
    # Переходим на страницу со списком питомцев после удаления
    success_url = reverse_lazy('dogs:list_dogs')
    # ------------------------------------------------------
    permission_required = 'dogs.delete_dog'
    # dogs.add_dog - PermissionRequiredMixin + CreateViwe
    # dogs.change_dog - PermissionRequiredMixin + UpdateViwe
    # dogs.view_dog - PermissionRequiredMixin + DetailViwe
    # ------------------------------------------------------


def dog_toggle_activity(request, pk):
    """ Переключение активности питомца."""
    dog_item = get_object_or_404(Dog, pk=pk)
    if dog_item.is_active:
        dog_item.is_active = False
    else:
        dog_item.is_active = True
    dog_item.save()

    return redirect(reverse('dogs:list_dogs'))

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        {% if user.is_superuser %}
                            <li><a class="p-2 btn btn-success" href="/admin/">Админка</a></li>
                        {% endif %}
                        <li><a href="{% url 'dogs:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'dogs:categories' %}" class="text-white">Породы</a></li>
                        <li><a href="{% url 'dogs:list_dogs' %}" class="text-white">Собаки</a></li>
                        <li><a href="{% url 'reviews:list_reviews' %}" class="text-white">Наши отзывы</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:users_list' %}" class="text-white">Все пользователи</a></li>
                            <li><a href="{% url 'users:profile_user' %}" class="text-white">Профиль</a></li>
                        {% include 'dogs/includes/inc_search_field.html' %}
                            <form method="post" action="{% url 'users:logout_user' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">Выход</button>
                            </form>
                        {% else %}
                            <li><a href="{% url 'users:login_user' %}" class="text-white">Вход</a></li>
                            <li><a href="{% url 'users:register_user' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Питомник</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

dogs/templates/dogs/categories.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'dogs/includes/inc_category.html' with object=object %}
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/create.html
{% extends 'dogs/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование собаки
                {% else %}
                Добавление собаки
                {% endif %}
            </div>

            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/delete.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
  <form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          {% if object %}
            Вы уверены что хотите удалить собаку
          {% endif %}
        </div>
        <div class="card-body">
          <img class="card-img-top" src="{{ object.photo|mymedia }}" width="300" height="320" alt="Card image cap" />
          <div class="card-body">
            <p class="card-text">{{ object.name|title }}</p>
          </div>
          <div class="card-footer">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-danger float-right">
              {% if object %}
                Удалить
              {% endif %}
            </button>
            <a href="{% url 'dogs:update_dog' object.pk %}" class="btn btn-outline-primary"><< Назад</a>
          </div>
        </div>
      </div>
    </div>
  </form>
{% endblock %}

dogs/templates/dogs/detail.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-md-4">
    <div class='card md-4 box-shadow'>
        <img class="card-img-top" src="{{ object.photo|mymedia }}" width="300" height="320" alt="Card image cap">
        <div class="card-body">
            <p class="card-text">
                <td>Кличка:</td>
                {{ object.name|title }}
            </p>
            <span class="text-muted"><td>Дата рождения: </td>{{ object.birth_date|default:"-" }}</span>
            <br>
            <span class="text-muted"><td>Хозяин: </td>{{ object.owner|default:"Без хозяина" }}</span>
            <br>
            <span class="text-muted"><td>Имя хозяина: </td>{{ object.owner.first_name }}</span>
            {% if object.owner.phone is not none %}
                <br>
                <span class="text-muted"><td>Телефон хозяина: </td>{{ object.owner.phone }}</span>
            {% endif %}
             <br>
            <span class="text-muted"><td>Просмотры: </td>{{ object.views }}</span>

        </div>
        <div class="card-footer">
            <a class="btn btn-link" href="{% url 'dogs:list_dogs' %}">назад</a>
            {% if user.is_satff or user == object.owner %}
            <a class="btn btn-link" href="{% url 'dogs:update_dog' object.pk %}">обновить</a>
            <a class="btn btn-link" href="{% url 'dogs:delete_dog' object.pk %}">удалить</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}


<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'dogs/includes/inc_dog_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' %}
    <a href="{% url 'dogs:create_dog' %}" class="btn btn-outline-primary m-2 float-left">Добавить собаку</a>
    <a href="{% url 'dogs:deactivated_list_dogs' %}" class="btn btn-outline-secondary m-2 float-right">Не активные
        собаки</a>
    <a href="{% url 'dogs:list_dogs' %}" class="btn btn-outline-success m-2 float-right">Активные собаки</a>

</div>
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}
{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'dogs/includes/inc_category.html' with object=object %}
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/update.html
{% extends 'dogs/base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          {% if object %}
            Редактирование собаки
          {% else %}
            Добавление собаки
          {% endif %}
        </div>

        <div class="card-body">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" class="btn btn-outline-success" 

          value="{% if object %}Сохранить{% else %} Добавить{% endif %}">
             {% if object %}
          <a href="{% url 'dogs:toggle_activity_dog' object.pk %}" 
          class="btn btn-outline-warning float-right">
        {% if object.is_active%}
        Деактивировать
        {% else %}
        Активировать
        {% endif %}
         </a>
         {% endif %}
        </div>
        <div class="card-footer">
          <a href="{% url 'dogs:list_dogs' %}" class="btn btn-outline-primary"><< Назад</a>
           {% if object and user.is_superuser %}
            <a href="{% url 'dogs:delete_dog' object.pk %}" class="btn btn-outline-danger float-right">Удалить</a>
        {% endif %}
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">Родословная</div>
        <div class="card-body">
            {{ formset.management_form }}
            {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                    <hr>
                {% endif %}
            {% endfor %}
        </div>
      </div>
    </div>
  </form>
{% endblock %}