config/urls.py
"""
Настройка URL-адресов для проекта config.

Список `urlpatterns` перенаправляет URL-адреса в представления. Для получения дополнительной информации, пожалуйста, смотрите:
 https://docs.djangoproject.com/en/5.0/topics/http/urls/
Примеры:
Функциональные представления
 1. Добавьте импорт: из my_app импортируйте представления
 2. Добавьте URL-адрес в urlpatterns: path(", views.home, name="home")
Представления на основе классов
 1. Добавьте импорт: из other_app.views импортируйте Home
 2. Добавьте URL-адрес в urlpatterns: path(", Home.as_view(), name="home")
Включая другой URLconf
 1. Импортируйте функцию includes(): из django.urls импортируйте includes, path
 2. Добавьте URL-адрес в urlpatterns: path('blog/', includes('blog.urls'))
"""
"""Отслеживание url-адресов"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# urls для административной панели Django
urlpatterns = [
                  path('admin/', admin.site.urls),  # URL для административной панели Django
                  path('', include('dogs.urls', namespace='dogs')),  # URL для приложения dogs
                  path('users/', include('users.urls', namespace='users')),  # URL для приложения users)
                  path('reviews/', include('reviews.urls', namespace='reviews')),  # URL для приложения reviews)
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Добавляем медиафайлы

dogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page,never_cache

from dogs.models import Category
from dogs.views import index, DogListView, DogCreateView, DogDetailView, DogUpdateView, DogDeleteView, \
    DogCategoryListView, CategoryListView, DogDeactiveListView, DogSearchListView, dog_toggle_activity, \
    CategorySearchListView
from dogs.apps import DogsConfig

app_name = DogsConfig.name  # DogsConfig имя приложения

urlpatterns = [
    path('', cache_page(60)(index), name='index'),  # url на главную страницу  /кешируется страница 
    path('categories/', cache_page(60)(CategoryListView.as_view()), name='categories'),  # url на страницу с информацией о всех категориях
    path('categories/<int:pk>/dogs/', DogCategoryListView.as_view(), name='category_dogs'), # url на страницу с информацией о питомцах определенной кат
    path('dogs/', DogListView.as_view(), name='list_dogs'),  # url на страницу с информацией о всех питомцах (вместо pk)
    path('dogs/deactivated/', DogDeactiveListView.as_view(), name='deactivated_list_dogs'),  # url на страницу с информацией о всех не активных питомцах (вместо pk)
    path('dogs/search/', DogSearchListView.as_view(), name='search_dogs'),
    path('categories/search/', CategorySearchListView.as_view(), name='search_category'),
    path('dogs/create', DogCreateView.as_view(), name='create_dog'), # url на страницу создания нового питомца
    path('dogs/detail/<int:pk>/', DogDetailView.as_view(), name='detail_dog'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='update_dog'), # /не кешируется страница
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='toggle_activity_dog'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='delete_dog')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_generate_new_password, UserRegisterView, UserLoginView, UserProfileView, UserUpdateView, \
    UserPasswordChangeView, UserLogoutView, UserListView, UserViewProfileView

app_name = UsersConfig.name

urlpatterns = [
    # работа с аккаунтом
    path('', UserLoginView.as_view(), name="login_user"),
    path('logout/', UserLogoutView.as_view(), name='logout_user'),
    path('register/', UserRegisterView.as_view(), name='register_user'),
    path('profile/', UserProfileView.as_view(), name='profile_user'),
    path('update/', UserUpdateView.as_view(), name='update_user'),
    path('change_password/', UserPasswordChangeView.as_view(), name='change_password_user'),
    path('profile/genpassword/', user_generate_new_password, name='generate_new_password_user'),

    # просмотр других пользователей
    path('all_users/', UserListView.as_view(), name='users_list'),
    path('profile/<int:pk>/', UserViewProfileView.as_view(), name='profile_user_view'),
]

users/models.py
# Описание моделей
from django.db import models
from django.contrib.auth.models import  AbstractUser
from django.utils.translation import gettext_lazy as _

# настройка полей, чтобы возможно было заполнить поля пустыми
NULLABLE ={'blank': True, 'null': True}

class UserRoles(models.TextChoices):
    """ Роли пользователь """
    ADMIN = 'admin', _('admin')
    MODERATOR = 'moderator', _('moderator')
    USER = 'user', _('user')

class User(AbstractUser):
    """Модель пользователя с полями email, телефон и Telegram username."""
    username = None
    email = models.EmailField(unique=True,verbose_name='email')
    role = models.CharField(max_length=9, choices=UserRoles.choices, default=UserRoles.USER)
    first_name = models.CharField(max_length=150, verbose_name='First Name',default="Anonymous")
    last_name = models.CharField(max_length=150, verbose_name='Last Name', default="Anonymous")
    phone = models.CharField(max_length=35, verbose_name='Phone number', **NULLABLE)
    telegram = models.CharField(max_length=150, verbose_name='Telegram Username', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Avatar', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='active', help_text='Активный пользователь')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return  f'{self.email}'

    class Meta:
        verbose_name = 'User'
        verbose_name_plural ='User'
        ordering = ['id']

users/forms.py
from django import forms


from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, AuthenticationForm

from users.models import User
from users.validators import validate_password

class StyleFromMixin:
    """Миксин для добавления стилей к формам."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFromMixin, forms.ModelForm):
    """Форма редактирования профиля пользователя."""

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone',)


class UserRegisterForm(StyleFromMixin, UserCreationForm):
    """ Форма для регистрации нового пользователя."""

    class Meta:
        # Поля модели User
        model = User
        fields = ('email',)

    def clean_password2(self):
        # Проверка соответствия паролей
        cd = self.cleaned_data
        validate_password(cd['password1'])
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('password_mismatch')
        return cd['password2']


class UserLoginForm(StyleFromMixin, AuthenticationForm):
    """ Форма для авторизации пользователя."""
    pass


class UserUpdateForm(StyleFromMixin, forms.ModelForm):
    """ Форма для изменения пользователя."""

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',
                  'phone', 'telegram', 'avatar',)


class UserPasswordChangeForm(StyleFromMixin, PasswordChangeForm):
    """ Форма для смены пароля."""

    def clean_new_password2(self):
        # Проверка соответствия паролей
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")
        validate_password(password1)
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
                )
        password_validation.validate_password(password2, self.user)
        return password2

users/views.py
import random
import string

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.base import Model as Model
from django.shortcuts import reverse, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from users.models import User
from users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm, UserPasswordChangeForm, UserForm
from users.services import send_register_email, send_new_password


class UserRegisterView(CreateView):
    """ Регистрация пользователя."""
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login_user')
    template_name = 'user/register_user.html'

    def form_valid(self, form):
        # переписываем form_valid для отправки письма при регестрации
        self.object = form.save()  # получаем объект из формы
        send_register_email(self.object.email)  # отправляем письмо  на почту объекта
        return super().form_valid(form)


class UserLoginView(LoginView):
    """ Логин пользователя."""
    template_name = 'user/login_user.html'
    form_class = UserLoginForm


class UserProfileView(UpdateView):
    """ Изменение профиля пользователя."""
    model = User
    form_class = UserForm
    template_name = 'user/user_profile_read_only.html'

    def get_object(self, queryset=None):
        return self.request.user


class UserLogoutView(LogoutView):
    """ Выход пользователя."""

    template_name = 'user/logout_user.html'


class UserUpdateView(UpdateView):
    """ Изменение профиля пользователя."""
    model = User
    form_class = UserUpdateForm
    template_name = 'user/update_user.html'
    success_url = reverse_lazy('users:profile_user')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChangeView(PasswordChangeView):
    """ Изменение пароля пользователя."""
    form_class = UserPasswordChangeForm
    template_name = 'user/change_password_user.html'
    success_url = reverse_lazy('users:profile_user')


class UserListView(LoginRequiredMixin, ListView):
    """ Список всех заводчиков."""
    model = User
    paginate_by = 3
    extra_context = {
        'title': 'Питомник. Все наши заводчики'
    }
    template_name = 'user/users.html'

    def get_queryset(self):
        # фильтр показывает только активных пользователей
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class UserViewProfileView(DetailView):
    """ Просмотр профиля пользователя."""
    model = User
    template_name = 'user/user_view_profile.html'

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def user_generate_new_password(request):
    # генерация нового пароля и отправка его на почту
    new_password = ''.join(random.sample(
        (string.ascii_letters + string.digits), 12))
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('dogs:index'))

users/templates/user/change_password_user.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Изменение пароля</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/user/login_user.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Авторизация пользователя</div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/user/logout_user.html
{% extends 'dogs/base.html' %}

{% block content %}
<h1>Вы вышли  из вашего аккаунта.</h1>
<p>Спасибо за использование нашего сервиса.</p>
<a href={% url 'users:login_user' %}>Нажмите чтобы сново войти</a>
{% endblock %}

users/templates/user/register_user.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Регистрация пользователя</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/user/update_user.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Редактирование пользователя</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/user/user_profile.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Профиль пользователя</div>
            <img class="card-img-top"
                 src="{{ user.avatar|user_media }}" width="300" height="700"
                 alt="Card image cap">
            <div class="card-body">
                <form enctype="multipart/form-data">
                    {{ form.as_p }}
                    <button class="btn btn-outline-warning">
                        <a class="btn btn-link" href="{% url 'users:update_user' %}">Обновить</a>
                    </button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/user/user_profile_read_only.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-header">Профиль пользователя</div>
                <img class="card-img-top"
                     src="{{ user.avatar|user_media }}" width="300" height="700"
                     alt="Card image cap">
                <div class="card-body">
                    <span class="card-text">Имя: {{user.first_name}}</span><br>
                    <span class="card-text">Фамилия: {{user.last_name}}</span><br>
                    <span class="card-text">Почта: {{user.email}}</span><br>
                    <span class="card-text">Телефон: {{user.phone|default:"не указано"}}</span><br>
                    <span class="card-text">Телеграмм: {{user.telegram|default:"не указано"}}</span><br>
                    <button class="btn btn-outline-primary">
                        <a class="btn btn-link" href="{% url 'users:update_user' %}">обновить</a>
                    </button>
                    <button class="btn btn-outline-warning">
                        <a class="btn btn-link" href="{% url 'users:change_password_user' %}">изменить пароль</a>
                    </button>
                    <button class="btn btn-outline-danger">
                        <a class="btn btn-link" href="{% url 'users:generate_new_password_user' %}">генерация пароля</a>
                    </button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/user/user_view_profile.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-header">Профиль {{ object.first_name }}</div>
                <img class="card-img-top"
                     src="{{ user.avatar|user_media }}" width="300" height="700"
                     alt="Card image cap">
                <div class="card-body"><span class="card-text"> Почта: {{ object.email }}</span><br>
                    <span class="card-text"> Имя: {{ object.first_name|default:"Не указано" }}</span><br>
                    <span class="card-text"> Фамилия: {{ object.last_name|default:"Не указано" }}</span><br>
                    <span class="card-text"> Телефон: {{ object.phone|default:"Не указано" }}</span><br>
                    <span class="card-text"> Telegram: {{ object.telegram|default:"Не указано" }}</span><br>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:users_list' %}" class="btn btn-outline-primary"> << Назад </a>
            </div>
        </div>

    </div>

{% endblock %}

users/templates/user/users.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'user/includes/inc_user_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' %}
</div>
{% endblock %}